#+title: Mysql高级
* gentoo
1. sudo emerge --config =dev-db/mysql-8.0.31-r1
2. rc-update add mysql default
3. rc-service mysql start
4. mysql_secure_installation
5. 禁用历史记录: ln -sf /dev/null ~/.mysql_history
** docker的phpmyadmin
1. 和远程访问一个道理，要想从容器中的phpMyAdmin访问运行在服务器上的MySQL，必须先修改MySQL配置文件，允许非localhost的IP访问。
   #+begin_src cnf
打开/etc/mysql/mysql.d/50-distro-server.cnf配置文件，进行如下修改：
bind-address = localhost
# 找到上式，修改为
bind-address = xxx.xx.xx.x # 你的docker0的ip地址
# 或者修改为
bind-address = 0.0.0.0 # 表示允许任意ip地址访问
   #+end_src
2. 然后，还需要将你的账号也设置为允许从远程登陆（默认为localhost）。为了完成这一操作，先通过localhost登入mysql，更改mysql数据库里的user表里对应你账号的host项，从localhost改成%。具体操作如下：
   #+begin_src sql
# 使用mysql数据库
use mysql;
# 将root账号（可替换成其他）的host修改为%
update user set host = '%' where user = 'root';
# 查看修改结果
select host, user from user;
   #+end_src
3. 最后，不要忘记重启mysql
4. 创建phpMyAdmin镜像
   #+begin_src shell
# PMA_HOST设置为连接的MySQL主机名或ip地址
# PMA_PORT设置为端口号
# 8080:80，将宿主机的8080端口映射到镜像的80端口
docker run -d \
    --name myadmin \
    -e PMA_HOST=$(ip route show | grep docker0 | awk '{print $9}') \
    -e PMA_PORT=3306 \
    -p 8080:80 \
    phpmyadmin/phpmyadmin
   #+end_src

   值得一提的是，这里是通过桥接网络模式（bridge mode）运行的镜像，因此在镜像中可通过docker0访问宿主网络。
5. 此时，可以通过8080端口访问到phpMyAdmin的管理界面了，即http://your_domain_name:8080/。
6. One More Thing

   把MySQL随意地暴露在网络下无疑会带来安全隐患，从安全角度考虑，应该为防火墙设置白名单规则，只有白名单的IP才能够连接数据库。

# ufw防火墙，提供一个参考思路而已
ufw insert 1 allow from 172.17.0.3 to any port 3306
* 技巧
1. %和_是通配符
2. show variables like 'skip_name';
   - skip_name_resolve = on 禁止主机名解析,建议使用
   - 查询变量,*gentoo无此变量*
   - show variables like '___';
     查询3个字符的变量
3. create database if not exists db1;
   *数据库存在也不会报错*
   - drop database if exists db1;
4. create database db2 default charset utf8mb4;
   *指定字符集*
5. 查看字符集
   1. 查看表的字符集
      show create table table;
   2. 查看库的字符集
      show create database database;
   3. 查看DBMS的字符集
      show variables like 'character_%';
   4. 查看比较规则
      show variables like 'collation_%';
6. 脚本模式
   1. mysql -uroot -pf < /path/to/somefile.sql
   2. mysql> source somefile.sql
7. 去重:distinct
   #+begin_src sql
 use test;
 create table repetition(id int);
 insert into repetition values(1);
 insert into repetition values(1);
 insert into repetition values(1);
 select * from repetition;
 select distinct * from repetition;
   #+end_src
8. 着重号 ``
   如果出现了字段名,表名跟关键字重名,要明确加上着重号,表示就是一个普通的字段,表名
9. 查询常数
   select '尚硅谷',student_id,student_name from school;
   查询尚硅谷的全部学生(全部学生都在尚硅谷)
10. select database();
* root@localhost
- root@localhost和root@127.0.0.1是不同账号
- 前者走socket,后者走tcp/ip
* 修改mysql的PS1
- man mysql
  #+begin_quote
       •   Use an option file.  You can set the prompt option in the [mysql] group of any MySQL option file, such as /etc/my.cnf or the .my.cnf file in your home directory. For
           example:

               [mysql]
               prompt=(\\u@\\h) [\\d]>\\_
  #+end_quote
* 常用选项
1. -A 禁止补全
2. -P port
3. -S socket
4. -D 指定默认数据库
   - 默认不写也是
     - mysql -uroot -pf mysql
5. -C 启用压缩
6. -e 执行sql命令
   - mysql -uroot -pf -e "show databases;status;"
7. -V 查看版本
8. -v verbose
9. --print-defaults
   获取程序默认使用配置
   - mysql --print-defaults
   - mysqld --print-defaults
* 配置文件
- _和-相同
- 0,OFF,FALSE意义相同,1,ON,TRUE意义相同
- mysqld: skip-network=1
  - 关闭网络
  - 3306端口将关闭
  - 但本地仍然可以通过socket连接
  - 南要重启服务
* 二进制安装
1. useradd -r -d /data/mysqldb -s /sbin/nologin mysql
   *系统账号默认不会创建家目录*
2. tar xvf mariadb-num-linux-x86_64,tar.gz -C /usr/local/
3. cd /usr/local/
4. ln -s mariadb-num-linux-x86_64,tar.gz mysql
5. chow -R root: mysql/
6. 将/usr/local/mysql/bin加入环境变量
7. mkdir /data/mysqldb
8. chown mysql.mysql /data/mysqldb
9. chmod 770 /data/mysqldb
10. cp support-files/my-huge.cnf /etc/my.cnf
    选择my-huge.cnf作为主要配置
11. scripts/mysql_install_db --datadir=/data/mysqldb --user=mysql
    生成数据库文件
    - 可能需要安装的包
      1. perl-Data-Dumper
      2. libaio
12. 修改配置文件,在配置文件中指定数据库
    #+begin_src cnf
[mydqld]
datadir = /data/mysqldb
socket = /usr/local/mysql/mysql.sock
[client]
socket = /usr/local/mysql/mysql.sock
    #+end_src
13. cp support-files/mysql.server /etc/init.d/mysqld
    拷贝服务文件
14. chkconfig --add mysqld
    开机启动
15. service mysqld start
    由于sock文件在/usr/local/mysql/mysql.sock没有写权限,启动失败
16. setacl -R -m u:mysql:rwx /usr/local/mysql/
17. mysql_secure_installation
    取消sock路径的修改
* 子命令help
- system: 执行shell命令
  - system hostname
  - 或 \! hostname
- status
  - 查看状态
  - 包括版本,当前用户,当前使用数据库,编码
  - 或\s
* 客户端命令与服务器命令
1. 客户端命令
   - 通过客户端执行
   - help下的命令
   - *不需要加分号*
2. 服务器命令
   - 服务器端执行
   - *需要加分号*
* 命令
- 查看用户: select user();
** mysqladmin
- mysqladmin -uroot -pf password mysql
  - mysqladmin -uroot -pmysql password
- mysqladmin -uroot -pf *create* db1
  - mysqladmin -uroot -pf drop db1
- mysqladmin -uroot -pf *ping*
  - mysqladmin -uroot -pf ping &> /dev/null || systemctl restart mariadb
- mysqladmin -uroot -pf shutdown
* 对应关系
1. 1对多

   员工表的部门id和部门表的id,1个部门有多个员工

   - 外键表信赖于主键表,员工表的department_id信赖于部门表的id
     所以id是主键,department_id是外键

2. 多对多

   学生表(student)课程表(course)

   - 分别取出学生id和课程id组成第三张表
     sid信赖学生数目,cid信赖课程数目,都是外键
* 多表查询
- 简单的多表查询
  #+begin_src sql
  select emp.employee_id,dept,depart_name,emp.department_id
  from employees emp,departments dept
  where emp.department_id = dept.department_id;
  -- 当员工的部门id和部门表的部门id相等时,打印部门名字
  #+end_src
  - employees:职位表 departments:公寓表
- 等值连接,非等值连接
  #+begin_src sql
  select e.last_name,e.salary,j.grade_level
  from employees e,job_grades j
  where e.salary >= j.lowest_sal and e.highest_sal;
  -- 当员工工资在某个区间上时,打印工资等级
  #+end_src
  - employees:职位表 job_grades:公资等级表
- 自连接,非自连接
  #+begin_src sql
select emp.employee_id,emp.last_name,mgr.employee_id,mgr.last_name
fron employees emp,employees mgr
where emp.manager_id = mgr.employee_id;
-- 当员工的管理者id和员工id相等时,查询管理者id和名字
  #+end_src
- 内连接
  #+begin_src sql
  select emp.employee_id,dept,depart_name,emp.department_id
  from employees emp join departments dept
  on emp.department_id = dept.department_id;
  -- 当员工的部门id和部门表的部门id相等时,打印部门名字
  #+end_src
- 左外连接
  #+begin_src sql
  select emp.employee_id,dept,depart_name,emp.department_id
  from employees emp left join departments dept
  on emp.department_id = dept.department_id;
  -- 当员工的部门id和部门表的部门id相等时,打印部门名字
  #+end_src
- 右外连接
  #+begin_src sql
  select emp.employee_id,dept,depart_name,emp.department_id
  from employees emp right join departments dept
  on emp.department_id = dept.department_id;
  -- 当员工的部门id和部门表的部门id相等时,打印部门名字
  #+end_src
- union,union all
  连接两个表,但union会去重
- 满外连接
* 规范
1. 字符串单引,列别名双引
2. 关键字大写
* 普通语法
1. 注释
   1. #
   2. /*  */
   3. -- (其它数据库通用)
2. 转义符:\
* databases
- show databases;
- create database database;
- use database;
- drop database database;
* tables
  describe table;
- show tables;
- create table table(id int,name varchar(15));
- insert into table values(1,'Tom');
- select * from table;
- 显示表结构
  1. describe table;
  2. desc table;
* select
#+begin_src sql
select 5+4;
select 5+4 from dual;
#+end_src
- select 字断名 from 表名;
  #+begin_src sql
use mysql;
select cost_name,last_update from engine_cost;
  #+end_src
- 列的别名
  #+begin_src sql
use mysql;
select cost_name cname,last_update lupdate from engine_cost;
select cost_name AS cname,last_update AS lupdate from engine_cost;
select cost_name AS "cost名",last_update AS "日期" from engine_cost;
  #+end_src
  *别名用双引*
- 空值参于运算
  #+begin_src sql
create table NULLoperation(value int,times int);
show create table NULLoperation\G
select value,times,value*times from NULLoperation;
insert into NULLoperation values(3,null);
select value,times,value*times from NULLoperation;
select value,times,value*ifnull(times,0) from NULLoperation;
-- 空植用零替换: ifnull(times,0)
  #+end_src
  *空值参于运算的结呆一定为空*
  *空值不等于零*
- 过滤条件
  #+begin_src sql
select 1,value,times,value*ifnull(times,1) from NULLoperation where times=10;
  #+end_src
  *where放在from的后面*
* 比较
- 不等于:<>,同!=
- 安全等于:*<=>*
  可以对NULL进行判断,而不返回NULL,等号有NULL参于就返回NULL
- is null, is not null, isnull()
- least(), greatest()
- beteen and 包含边界
- in (), not in ()
- not/!, and/&&, or/||, xor(逻辑异或)
  *not用在where后面
- like:模糊查询
  - *like放在where后面过滤输出结果,多个条件用or,and*
    select 1,value,times,value*ifnull(times,1) from NULLoperation where times like '1%';
  - select from where like '%a%'
    *%号同linux的星*
  - select from where like '_a%' (查询第二个字符是a的结果)
    *_同正则表达式的点*
- regexp/rlike:正则表达式
  - *regexp/rlike放在where后面过滤输出结果,多个条件用or,and*
    select 1,value,times,value*ifnull(times,1) from NULLoperation where times regexp '1.';
* 排序
- order by 字段 [asc] (ascend)
- order by 字段 desc (descend)
- 列的别名只能在order by中使用,不能在where中使用
- 二级排序
  *在一级排序的结果相同时,再进行排序*
  - order by 字段 desc 字段 [asc]
    *升序可省略asc
* 分页
- limit 偏移量,条数
  - eg limit [0],20 (每页显示20条数据,此时显示第1页)
    *偏移量为零可省略*
  - eg limit 20,20 (每页显示20条数据,此时显示第2页)
  - eg limit 40,20 (每页显示20条数据,此时显示第3页)
    公式: limit (pageNo-1)*pageSize,pageSize;
- mysql8.0新特性: limit 条数 offset 偏移量
* 约束
- 主键约束
  #+begin_src sql
create table user(
             id int primary key auto_increment comment '主键',
             name varchar(10) not null unique comment '姓名',
             age int check ( age > 0 && age <= 120 ) comment '年龄',
             status char(1) default '1' comment '状态',
             gender char(1) comment '性别'
) comment '用户表';

  #+end_src

- 外键约束
  #+begin_src sql
alter table emp add constraint fk_emp_dept_id foreign key (dept_id) references dept(id);
  #+end_src
  - emp表的dept_id信赖dept表的id
  - 删除
    #+begin_src sql
alter table emp drop foreign key fk_emp_dept_id
    #+end_src
* 事务
- 查询
  #+begin_src sql
(root@localhost) [test]> select @@autocommit;
+--------------+
| @@autocommit |
+--------------+
|            1 |
+--------------+
1 row in set (0.00 sec)
  #+end_src
- set @@autocommit = 0;
  手动提交
  #+begin_src sql
set @@autocommit = 0;
commit;
-- 回滚事务
rollback;
  #+end_src
- start transaction;
- 事务隔离级别
  - 查询
    #+begin_src sql
    (root@localhost) [test]>  select @@transaction_isolation;
    +-------------------------+
    | @@transaction_isolation |
    +-------------------------+
    | REPEATABLE-READ         |
    +-------------------------+
    1 row in set (0.00 sec)
    #+end_src
  - set session transaction isolation level read_uncommitted;
* 日志
- 二进制日志
  *对库的修改*
  #+begin_src sql
(root@localhost) [(none)]> show variables like '%log_bin%';
+---------------------------------+---------------------------------+
| Variable_name                   | Value                           |
+---------------------------------+---------------------------------+
| log_bin                         | ON                              |
| log_bin_basename                | /var/lib/mysql/gentoo-bin       |
| log_bin_index                   | /var/lib/mysql/gentoo-bin.index |
| log_bin_trust_function_creators | OFF                             |
| log_bin_use_v1_row_events       | OFF                             |
| sql_log_bin                     | ON                              |
+---------------------------------+---------------------------------+
6 rows in set (0.00 sec)
  #+end_src
  - 查看日志格式
    #+begin_src sql
(root@localhost) [(none)]> show variables like '%binlog_format';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| binlog_format | ROW   |
+---------------+-------+
1 row in set (0.01 sec)
    #+end_src
  - mysqlbinlog gentoo-bin.000003 -v
    格式为ROW要加-v
  - 删除日志
    - reset master
      删除全部
    - purge master logs to 'binlog.***'
      删除***之前的所有日志
    - purge master logs before 'yyyy-mm-dd hh:mm:ss'
  - 过期时间
    #+begin_src sql
(root@localhost) [(none)]> show variables like '%binlog_expire%';
+-------------------------------+---------+
| Variable_name                 | Value   |
+-------------------------------+---------+
| binlog_expire_logs_auto_purge | ON      |
| binlog_expire_logs_seconds    | 2592000 |
+-------------------------------+---------+
2 rows in set (0.00 sec)
    #+end_src
    30天后会自动删除
- 查询日志
  *对库的查询*
  #+begin_src sql
(root@localhost) [(none)]> show variables like '%general%';
+------------------+---------------------------+
| Variable_name    | Value                     |
+------------------+---------------------------+
| general_log      | OFF                       |
| general_log_file | /var/lib/mysql/gentoo.log |
+------------------+---------------------------+
2 rows in set (0.00 sec)
  #+end_src
  *查询日志默认关闭*
- 慢查询日志
  - 开启慢查询
    #+begin_src cnf
#开启慢查询
slow_query_log=1
#慢查询时间参数
long_query_time=2
    #+end_src
* 主从复制
- 主库配置
  1. /etc/my.cnf
    #+begin_src cnf
server-id=1
read-only=0
    #+end_src
  2. 创建用户
     #+begin_src sql
create user 'f'@'%' identified with mysql_native_password by 'f';
     #+end_src
  3. 授于权限
     #+begin_src sql
grant replication slave on *.* to 'f'@'%';
     #+end_src
  4. 查看二进制日志坐标
     #+begin_src sql
show master status;
     #+end_src
- 从库配置
  1. /etc/my.cnf
    #+begin_src cnf
server-id=2
read-only=1
    #+end_src
  2. 8.0.23之前
     #+begin_src sql
change replication source to source_host='xxx.xxx',source_user='xxx',source_log_file='xxx',source_log_pos=xxx;
     #+end_src
     如果是8.0.23之前的版本,执行如下sql:
     #+begin_src sql
change replication master to master_host='xxx.xxx',master_user='xxx',master_log_file='xxx',master_log_pos=xxx;
     #+end_src
  3. 开启同步操作
     #+begin_src sql
start replica; #8.0.22之后
start slave; #8.0.22之前
     #+end_src
  4. 查看主从同步状态
     #+begin_src sql
start replica status\G; #8.0.22之后
start slave status\G; #8.0.22之前
     #+end_src
     - 查看replica_io_running和replica_sql_running是否为yes
